org: rross
app: authentication-proxy
name: authentication-proxy
component: aws-lambda

functions:
  hello:
    handler: handler.router
    events:
      - http:
          path: payments
          method: any
          cors: true
      - http:
          path: policy
          method: any
          cors: true
