version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build

  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:unit

  integration-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:integration

  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm i -g serverless
            - run: sls deploy

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - integration-test
            - unit-test
