version: 2.1
defaults: &defaults
  working_directory: ~/repo
  executor:
    name: node/default

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/repo
          cache-path: node_modules
          override-ci-command: npm i
      - run: sudo npm i -g serverless
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  unit-test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test:unit

  integration-test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test:integration

  deploy_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sls deploy

  deploy_int:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sls deploy --stage int

  deploy_prd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sls deploy --stage prd

workflows:
  version: 2
  dev_build_test_deploy:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - deploy_dev:
          context: authentication_proxy
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - integration-test
            - unit-test

      - hold_int:
          type: approval
          requires:
            - deploy_dev

      - deploy_int:
          requires:
            - hold_int
          context: authentication_proxy
          filters:
            branches:
              only:
                - master

      - hold_prd:
          type: approval
          requires:
            - deploy_int

      - deploy_prd:
          context: authentication_proxy
          requires:
            - hold_prd
          filters:
            branches:
              only:
                - master
