version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build

  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:unit

  integration-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:integration

  deploy_dev:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm i -g serverless
            - run: npm run build
            - run: sls deploy

  deploy_int:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm i -g serverless
            - run: npm run build
            - run: sls deploy --stage int

  deploy_prd:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm i -g serverless
            - run: npm run build
            - run: sls deploy --stage prd

workflows:
  version: 2
  dev_build_test_deploy:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - deploy_dev:
          context: authentication_proxy
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - integration-test
            - unit-test

      - hold_int:
          type: approval
          requires:
            - deploy_dev

      - deploy_int:
          requires:
            - hold_int
          context: authentication_proxy
          filters:
            branches:
              only:
                - master

      - hold_prd:
          type: approval
          requires:
            - deploy_int

      - deploy_prd:
          context: authentication_proxy
          requires:
            - hold_prd
          filters:
            branches:
              only:
                - master